import React, { useState, useEffect } from 'react';
import { experimentAPI } from '../services/api';
import toast from 'react-hot-toast';

export default function DownloadReport() {
  const [sessions, setSessions] = useState([]);
  const [selected, setSelected] = useState('');
  const [reportData, setReportData] = useState(null);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    experimentAPI.history().then(r => { setSessions(r.data); if (r.data.length > 0) setSelected(r.data[0]._id); }).catch(() => {});
  }, []);

  const loadReport = async () => {
    if (!selected) { toast.error('Select a session'); return; }
    setGenerating(true);
    try {
      const { data } = await experimentAPI.report(selected);
      setReportData(data);
    } catch (err) { toast.error('Failed to load report'); }
    finally { setGenerating(false); }
  };

  const downloadHTML = () => {
    if (!reportData) return;
    const s = reportData;
    const metricsHTML = Object.entries(s.metrics || {}).map(([k, v]) =>
      `<tr><td style="padding:6px 12px;color:#a78bfa;">${k.replace(/_/g,' ')}</td><td style="padding:6px 12px;color:#e2e8f0;font-family:monospace;">${v < 1 && k !== 'mse' && k !== 'mae' ? (v*100).toFixed(2)+'%' : v}</td></tr>`
    ).join('');
    const stepsHTML = (s.preprocessingSteps || []).map((st, i) =>
      `<li style="color:#c4b5fd;font-size:12px;">Step ${i+1}: ${st.type} on "${st.column}" (${st.strategy || st.method})</li>`
    ).join('');
    const fiHTML = (s.featureImportance || []).slice(0,8).map((f, i) =>
      `<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
        <span style="color:#a78bfa;font-size:11px;width:120px;overflow:hidden;text-overflow:ellipsis;">${f.feature}</span>
        <div style="flex:1;height:8px;background:#1e1b4b;border-radius:4px;overflow:hidden;">
          <div style="width:${f.importance*100}%;height:100%;background:#7c3aed;border-radius:4px;"></div>
        </div>
        <span style="color:#c4b5fd;font-size:11px;font-family:monospace;width:50px;">${f.importance.toFixed(4)}</span>
      </div>`
    ).join('');
    const html = `<!DOCTYPE html><html><head><title>ML Report — ${s.modelType}</title>
<style>body{margin:0;padding:32px;background:#0f0a1e;color:#e2e8f0;font-family:'Segoe UI',monospace;}
h1{color:#a78bfa;font-size:24px;margin-bottom:4px;}
h2{color:#7c3aed;font-size:14px;text-transform:uppercase;letter-spacing:1px;margin-top:24px;margin-bottom:12px;border-bottom:1px solid #2d1b69;padding-bottom:6px;}
table{width:100%;border-collapse:collapse;background:#1a1030;border-radius:8px;overflow:hidden;}
th{background:#2d1b69;color:#a78bfa;padding:8px 12px;text-align:left;font-size:12px;}
.card{background:#1a1030;border:1px solid #2d1b69;border-radius:8px;padding:16px;margin-bottom:16px;}
.badge{display:inline-block;background:#2d1b69;color:#a78bfa;padding:2px 8px;border-radius:4px;font-size:11px;}
</style></head><body>
<h1>ML Experiment Report</h1>
<p style="color:#6b21a8;font-size:12px;">Generated ${new Date().toLocaleString()}</p>
<div class="card">
<h2>Experiment Info</h2>
<table><tr><th>Field</th><th>Value</th></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Model</td><td style="padding:6px 12px;color:#e2e8f0;">${s.modelType?.replace(/_/g,' ')}</td></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Dataset</td><td style="padding:6px 12px;color:#e2e8f0;">${s.datasetName || 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Target Column</td><td style="padding:6px 12px;color:#e2e8f0;">${s.targetColumn}</td></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Task Type</td><td style="padding:6px 12px;color:#e2e8f0;">${s.taskType}</td></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Split Ratio</td><td style="padding:6px 12px;color:#e2e8f0;">${s.splitRatio}</td></tr>
<tr><td style="padding:6px 12px;color:#a78bfa;">Trained At</td><td style="padding:6px 12px;color:#e2e8f0;">${new Date(s.createdAt).toLocaleString()}</td></tr>
</table></div>
<div class="card"><h2>Evaluation Metrics</h2><table><tr><th>Metric</th><th>Value</th></tr>${metricsHTML}</table></div>
${stepsHTML ? `<div class="card"><h2>Preprocessing Pipeline</h2><ol style="margin:0;padding-left:20px;">${stepsHTML}</ol></div>` : ''}
${fiHTML ? `<div class="card"><h2>Feature Importance</h2>${fiHTML}</div>` : ''}
<p style="color:#2d1b69;font-size:10px;margin-top:32px;text-align:center;">Generated by VizLearn — ML Visualization Platform</p>
</body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url;
    a.download = `ml-report-${s.modelType}-${Date.now()}.html`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  const downloadJSON = () => {
    if (!reportData) return;
    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url;
    a.download = `ml-report-${reportData.modelType}-${Date.now()}.json`; a.click();
    URL.revokeObjectURL(url);
    toast.success('JSON exported!');
  };

  return (
    <div style={{ fontFamily: "'JetBrains Mono', monospace" }}>
      <h1 className="text-xl font-bold text-violet-100 mb-1">Download Report</h1>
      <p className="text-violet-500 text-xs mb-6">Export experiment results</p>

      <div className="bg-gray-900/40 border border-violet-900/20 rounded-xl p-4 mb-4">
        <div className="flex items-end gap-3">
          <div className="flex-1">
            <label className="text-violet-500 text-xs uppercase tracking-wider block mb-2">Select Experiment</label>
            <select value={selected} onChange={e => setSelected(e.target.value)}
              className="w-full bg-slate-900 border border-violet-800/30 rounded-lg px-3 py-2.5 text-violet-200 text-xs focus:outline-none focus:border-violet-500">
              {sessions.map(s => (
                <option key={s._id} value={s._id}>
                  {s.modelType?.replace(/_/g,' ')} — {s.datasetName} ({new Date(s.createdAt).toLocaleDateString()})
                </option>
              ))}
            </select>
          </div>
          <button onClick={loadReport} disabled={generating || !selected}
            className="bg-violet-600 hover:bg-violet-500 text-white px-4 py-2.5 rounded-lg text-xs font-medium disabled:opacity-40">
            {generating ? 'Loading...' : 'Load Report'}
          </button>
        </div>
      </div>

      {reportData && (
        <div className="space-y-4">
          <div className="bg-gray-900/40 border border-violet-500/30 rounded-xl p-4">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-violet-300 text-sm font-semibold">Report Preview</h2>
              <div className="flex gap-2">
                <button onClick={downloadHTML}
                  className="bg-violet-600 hover:bg-violet-500 text-white px-3 py-1.5 rounded-lg text-xs font-medium flex items-center gap-1">
                  ⬒ HTML Report
                </button>
                <button onClick={downloadJSON}
                  className="bg-gray-700 hover:bg-gray-600 text-white px-3 py-1.5 rounded-lg text-xs font-medium flex items-center gap-1">
                  {} JSON Export
                </button>
              </div>
            </div>

            <div className="grid grid-cols-3 gap-3 mb-4">
              {[
                { label: 'Model', value: reportData.modelType?.replace(/_/g,' ') },
                { label: 'Dataset', value: reportData.datasetName || 'N/A' },
                { label: 'Task', value: reportData.taskType },
                { label: 'Target', value: reportData.targetColumn },
                { label: 'Split', value: reportData.splitRatio },
                { label: 'Date', value: new Date(reportData.createdAt).toLocaleDateString() },
              ].map(s => (
                <div key={s.label} className="bg-violet-900/20 rounded-lg p-3">
                  <p className="text-violet-500 text-xs">{s.label}</p>
                  <p className="text-violet-200 text-xs font-medium mt-0.5 capitalize">{s.value}</p>
                </div>
              ))}
            </div>

            <div className="mb-4">
              <h3 className="text-violet-400 text-xs uppercase tracking-wider mb-2">Metrics</h3>
              <div className="grid grid-cols-4 gap-2">
                {Object.entries(reportData.metrics || {}).map(([k, v]) => (
                  <div key={k} className="bg-gray-900/60 rounded-lg p-2 text-center">
                    <p className="text-violet-500 text-xs capitalize">{k.replace(/_/g,' ')}</p>
                    <p className="text-violet-200 text-sm font-bold mt-0.5">
                      {v < 1 && k !== 'mse' && k !== 'mae' ? `${(v*100).toFixed(1)}%` : v}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {reportData.preprocessingSteps?.length > 0 && (
              <div>
                <h3 className="text-violet-400 text-xs uppercase tracking-wider mb-2">Preprocessing ({reportData.preprocessingSteps.length} steps)</h3>
                <div className="flex flex-wrap gap-2">
                  {reportData.preprocessingSteps.map((step, i) => (
                    <span key={i} className="text-xs bg-violet-900/30 text-violet-300 px-2 py-1 rounded border border-violet-800/20">
                      {i+1}. {step.type} → {step.column}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {!reportData && sessions.length === 0 && (
        <div className="text-center py-20 bg-gray-900/20 border border-violet-900/10 rounded-2xl">
          <p className="text-violet-600 text-4xl mb-3">⬒</p>
          <p className="text-violet-400 text-sm">No experiments found. Train a model first.</p>
        </div>
      )}
    </div>
  );
}
